filebeat.inputs:
  - type: log
    id: app-logs
    enabled: true
    paths:
      - /var/log/app/*.log
    fields:
      app: sample-web
    fields_under_root: true
    json.keys_under_root: true
    json.add_error_key: true

output.kafka:
  hosts: ["kafka:9092"]
  topic: "logs-app"
  partition.round_robin:
    reachable_only: true
  required_acks: 1
  compression: gzip

setup.template.enabled: false
setup.ilm.enabled: false
logging.to_files: false
